version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - REDIS_URL=redis://redis:6379/0
      - RELOAD=true
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    networks:
      - groupchat-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - groupchat-network

  # Frontend will be added in Phase 2
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend:/app
  #   depends_on:
  #     - backend
  #   networks:
  #     - groupchat-network

networks:
  groupchat-network:
    driver: bridge

volumes:
  redis-data:
